/**
 * ExportDrawer — the Daten-Explorer download dialog.
 *
 * A single view (no tabs): PNG/SVG download buttons on top, then CSV and
 * Excel as a stacked download list.
 *   - PNG (Bild)   — the live chart at 2× (image export)
 *   - SVG (Vektor) — the live chart as vector (image export)
 *   - Excel        — the complete CaRM workbook, a static file in public/
 *   - CSV          — the current filtered selection as a table
 *
 * When the dataset toggle is on "Informationswege" (the `sources*` views),
 * the Excel and CSV cards switch to the information-channels dataset:
 * the static `cannabismythen-informationswege.xlsx` and a long-format CSV
 * built from `information-sources.json`.
 *
 * PNG/SVG export the live chart; in Tabelle view (no chart) the buttons are
 * replaced by a note pointing the user to a chart view. Excel and CSV are
 * always available. Excel is a native `<a download>` to a static asset (mirrors
 * the PDF download in FactsheetPanel); the other three run through the
 * exporters in `lib/dashboard/export.ts`.
 *
 * Drawer variant is `'modal'` (centered on desktop ≥1024px, max-width
 * 720px; bottom-sheet on mobile <1024px).
 *
 * Filenames:
 *   - cannabismythen-{view}-{indicator}-{group}.{png|svg}
 *   - cannabismythen-{…}.csv
 *   - cannabismythen-daten.xlsx (static)
 */

import { useMemo } from 'react';
import { Download, FileSpreadsheet, Table } from 'lucide-react';
import type { CarmData, GroupId, Indicator, InformationSourcesData, Myth } from '../../../lib/dashboard/types';
import Drawer from '../../shared/Drawer';
import {
  downloadFullCSV,
  downloadFullSourcesCSV,
  downloadChartPng,
  downloadChartSvg,
  buildExportFilename,
  type ChartHandle,
} from '../../../lib/dashboard/export';
import { getCorrectnessColor } from '../../../lib/dashboard/colors';
import { t } from '../../../lib/dashboard/translations';

/** Static CaRM workbooks served from public/. The myth workbook is maintained
 *  by hand; the Informationswege workbook is generated by
 *  scripts/generate-informationswege-xlsx.py. */
const EXCEL_HREF = '/cannabismythen-daten.xlsx';
const EXCEL_FILENAME = 'cannabismythen-daten.xlsx';
const SOURCES_EXCEL_HREF = '/cannabismythen-informationswege.xlsx';
const SOURCES_EXCEL_FILENAME = 'cannabismythen-informationswege.xlsx';
const SOURCES_DATA_URL = '/data/information-sources.json';

/** Views that belong to the "Informationswege" dataset toggle. When one of
 *  these is active, the data downloads switch to the channels dataset. */
const SOURCES_VIEWS = new Set(['sources', 'sources2', 'sources_table']);

interface Props {
  open: boolean;
  onClose: () => void;
  /** Full myth list (filtered for the current view) — used by the CSV export. */
  myths: Myth[];
  /** Full metric list. */
  metrics: CarmData['metrics'];
  /** Current group selection — first id is used for image / CSV filenames. */
  groupIds: GroupId[];
  indicator: Indicator;
  /** Slug used in PNG / SVG filenames (e.g. 'balken', 'strips', 'sources'). */
  view: string;
  /** Full myth count (unfiltered) — lets the export filename detect the
   *  "whole deck" case (→ `rohdaten`) vs a filtered subset (CAR-4). */
  totalMyths?: number;
  /** Returns the active chart handle for image exports. May be `null` when
   *  the active view doesn't expose a chart (Tabelle). */
  getChart: () => ChartHandle | null;
  /** Chart chrome — title + subtitle baked into PNG / SVG. */
  chartChrome: () => { title: string; subtitle: string };
}

const VERDICT_LEGEND = [
  { verdict: 'richtig' as const, color: getCorrectnessColor('richtig'), key: 'verdict.richtig' as const },
  { verdict: 'eher_richtig' as const, color: getCorrectnessColor('eher_richtig'), key: 'verdict.eher_richtig' as const },
  { verdict: 'eher_falsch' as const, color: getCorrectnessColor('eher_falsch'), key: 'verdict.eher_falsch' as const },
  { verdict: 'falsch' as const, color: getCorrectnessColor('falsch'), key: 'verdict.falsch' as const },
];

export default function ExportDrawer({
  open,
  onClose,
  myths,
  metrics,
  groupIds,
  indicator,
  view,
  totalMyths,
  getChart,
  chartChrome,
}: Props) {
  const legend = useMemo(
    () => VERDICT_LEGEND.map((v) => ({
      verdict: v.verdict,
      color: v.color,
      label: t(v.key, 'de'),
    })),
    [],
  );
  const hasChart = !!getChart();
  const isSources = SOURCES_VIEWS.has(view);

  const handlePng = () => {
    const chart = getChart();
    if (!chart) return;
    const { title, subtitle } = chartChrome();
    downloadChartPng({
      chart,
      title,
      subtitle,
      legend,
      view,
      indicator,
      group: groupIds[0] ?? 'adults',
      myths,
      totalMyths,
    });
    onClose();
  };

  const handleSvg = () => {
    const chart = getChart();
    if (!chart) return;
    const { title, subtitle } = chartChrome();
    downloadChartSvg({
      chart,
      title,
      subtitle,
      legend,
      view,
      indicator,
      group: groupIds[0] ?? 'adults',
      myths,
      totalMyths,
    });
    onClose();
  };

  const handleCsv = () => {
    downloadFullCSV(
      myths, metrics, groupIds,
      buildExportFilename({
        kind: 'data', ext: 'csv', view, group: groupIds[0] ?? 'adults',
        myths, totalMyths,
      }),
    );
    onClose();
  };

  // Informationswege mode — the channels dataset lives in its own JSON,
  // fetched lazily on click. Long-format CSV of all channels × groups.
  const handleSourcesCsv = async () => {
    try {
      const res = await fetch(SOURCES_DATA_URL);
      const data = (await res.json()) as InformationSourcesData;
      downloadFullSourcesCSV(data, 'cannabismythen-informationswege.csv');
    } catch {
      // Network/parse failure — nothing actionable to surface in the dialog.
    }
    onClose();
  };

  return (
    <Drawer
      open={open}
      onClose={onClose}
      variant="modal"
      title={t('export.title', 'de')}
    >
      <p className="carm-export-intro">
        {t(isSources ? 'export.intro.sources' : 'export.intro', 'de')}
      </p>

      {/* Image exports — the live chart at 2× (PNG) or as vector (SVG).
          Shown only when the active view exposes a chart; in the Tabelle
          views (Mythen + Informationswege, which have no chart) the buttons
          are replaced by a note pointing at the diagram views. The Balken
          and Übersicht views in BOTH datasets do export images. */}
      {hasChart ? (
        <div className="carm-export-actions">
          <button type="button" className="carm-export-btn" onClick={handlePng}>
            <Download size={16} strokeWidth={2} aria-hidden="true" />
            {t('export.png.title', 'de')}
          </button>
          <button
            type="button"
            className="carm-export-btn carm-export-btn--ghost"
            onClick={handleSvg}
          >
            <Download size={16} strokeWidth={2} aria-hidden="true" />
            {t('export.svg.title', 'de')}
          </button>
        </div>
      ) : (
        <p className="carm-export-note" aria-live="polite">
          {t('export.images.note', 'de')}
        </p>
      )}

      {/* Data exports — CSV is the current filtered selection, Excel the
          full static workbook. CSV comes first per Fedor's order. */}
      <div className="carm-export-list">
        <ExportRow
          icon={<Table size={22} strokeWidth={1.75} />}
          title={t(isSources ? 'export.csv.title.sources' : 'export.csv.title', 'de')}
          desc={t(isSources ? 'export.csv.desc.sources' : 'export.csv.desc', 'de')}
          onClick={isSources ? handleSourcesCsv : handleCsv}
        />
        <ExportRow
          icon={<FileSpreadsheet size={22} strokeWidth={1.75} />}
          title={t(isSources ? 'export.excel.title.sources' : 'export.excel.title', 'de')}
          desc={t(isSources ? 'export.excel.desc.sources' : 'export.excel.desc', 'de')}
          href={isSources ? SOURCES_EXCEL_HREF : EXCEL_HREF}
          downloadName={isSources ? SOURCES_EXCEL_FILENAME : EXCEL_FILENAME}
          onClick={onClose}
        />
      </div>
    </Drawer>
  );
}

interface ExportRowProps {
  title: string;
  desc: string;
  /** Leading format icon. */
  icon: React.ReactNode;
  /** When set, the row renders as a download `<a>` (Excel static file). */
  href?: string;
  downloadName?: string;
  disabled?: boolean;
  onClick?: () => void;
}

/**
 * One row in the data-export list: a leading format icon, the title + 1-line
 * description, and a trailing download chip. Renders as an `<a download>`
 * when `href` is set (Excel), otherwise a `<button>`.
 */
function ExportRow({
  title,
  desc,
  icon,
  href,
  downloadName,
  disabled,
  onClick,
}: ExportRowProps) {
  const body = (
    <>
      <span className="carm-export-row__icon" aria-hidden="true">
        {icon}
      </span>
      <span className="carm-export-row__text">
        <span className="carm-export-row__title">{title}</span>
        <span className="carm-export-row__desc">{desc}</span>
      </span>
      <span className="carm-export-row__dl" aria-hidden="true">
        <Download size={16} strokeWidth={2} />
      </span>
    </>
  );

  if (href) {
    return (
      <a
        className="carm-export-row"
        href={href}
        download={downloadName}
        onClick={onClick}
      >
        {body}
      </a>
    );
  }

  return (
    <button
      type="button"
      className="carm-export-row"
      onClick={onClick}
      disabled={disabled}
    >
      {body}
    </button>
  );
}
